### ISSUE TITLE
Automatic colors are not always optimal when using only 2 colors

### ISSUE THREAD

**Issue by boogheta** [medialab/nansi#34]
When the attribute's name is type and we have only two colors, the two colors are very close, although this is quite a usual case whenever we want to do a bipartite graph, maybe add some "salt" to the seed for i want hue?

**Comment by Yomguithereal** [comment]
@boogheta I have added quality maximizing attempt heuristics in iwanthue. Now I keep the best palette out of 5 attempts, this should avoid bad local optima for randomly seeded iwanthue palette most of the time. I will let you test this on your own and close the issue.

**Comment by boogheta** [comment]
Confirmed!
